"""
COMP.CS.100 Ohjelmointi 1 / Programming 1
9.9 Project: Course Registry

Program Description: This program implements a data structure containing information about the courses offered by a university. The program should help a student to select suitable courses to enroll.

Author note: the docstring auto-generated by VSC is different than that of PyCharm
I hope you, the TA checking this, won't mind ^^

Author: Tri Phung
Student ID: K441912
Email: tri.phung@tuni.fi
"""

def main():
    print('Hello world')

if __name__ == "__main__":
    main()
